!Config
baseUri: http://psi.norge.no/los/
build:
- no.difi.data.skos.builder.build.RdfSingleBuild
- no.difi.data.skos.builder.build.RdfMultipleBuild
- no.difi.data.skos.builder.build.FreemarkerBuild
name: Los
options:
  github:
    repository: https://github.com/difi/los
    issues: https://github.com/difi/los/issues
